# latest stable version of Node.js
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get Node.js
  - ps: Install-Product node $env:nodejs_version
  # modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't build.
build: off
